
name : CI - Build Backend

on:
  pull_request:
    branches:
      - main
    paths:
      -backend/**
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15.4
        env:
          POSTGRES_USER: amigoscode
          POSTGRES_PASSWORD: password
          POSTGRES_DB: amigoscode
        ports:
          5332:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timout 5s
          --health-retries 5s

    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout#v3
      - uses: actions/setup-java#v3
        path:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name : Build and run Unit/Integration Tests with maven
        run : mvn -ntp -B verify

